# 端口
server:
  port: 8761
  #开启自我保护模式
  enable-self-preservation: false
  #清理无效节点,默认60*1000毫秒,即60秒
  eviction-interval-timer-in-ms: 5000
spring:
  application:
    name: eureka-server1
# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:${random.value}
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检查服务
    fetch-registry: false
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://localhost:8762/eureka
  logging:
    config: classpath:logback-spring.xml